### ISSUE TITLE
Guide for install

### ISSUE THREAD

**Issue by zero-pytagoras** [harvimt/pylib7zip#6]
Hello,
I am not able to find the package nowhere on pypi or debian based linux distributions. Can you update/provide instructions regarding installing the library ?

**Comment by harvimt** [comment]
It's not done... it's like 80% done, so it should mostly work, but a lot of what's not done is stuff to make it easy to install and use (there's no documentation for example)

Someone kindly submitted a linux version for example, which is in a different branch, but really both branches need to be merged so it worked on both windows and linux (and Mac, and BSD, etc.)

To install with pip, you should just be able to like `pip install git+https://github...` and just provide the git url

I haven't touched this code in many years. I think I'd still like to get it working 100% but the motivation I had (making a new mod manager for Oblivion) stopped when I stopped playing modded Oblivion.

Since I haven't touched it in many years it might for example only work with like Python 3.4 and whatever version of 7zip was current circa 2016.

As always with open source you're free to fork and fix it up so it works 100%.

**Comment by cielavenir** [comment]
@zero-pytagoras now `pip install git+https://github.com/cielavenir/pylib7zip.git@ciel` works, however you need 7zip 23 or later[^1]. 22 or below is not compatible.

[^1]: version restriction is only applied for macOS/Linux. On Windows both v22 and v23 work.
